# fly.toml app configuration file generated for nor-dev-comments-bot on 2023-10-13T16:21:28+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "nor-dev-comments-bot"
primary_region = "lhr"

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 1
  processes = ["app"]
